<?php

/**
 * To generate the "collage" for the home page
 *
 * 1. Finds all images in a certain album
 * 2. Downloads the image
 * 3. Converts the image to 400x400
 * 4. Generates a single image of all the images combined
 * 4. Generates a LESS file
 */

// Directory to store images in
$tmpDirectory = __DIR__ . '/tmp';

$lessFilePath = dirname(__DIR__).'/src/less/homepage-sprites.less';

$imgFilename = 'homepage-sprites-'.time().'.jpg';
$imgFileDir = dirname(__DIR__).'/public/assets/img';
passthru("rm {$imgFileDir}/homepage-sprites*");

if (!is_dir($tmpDirectory)) {
    mkdir($tmpDirectory);
}
chdir($tmpDirectory);
if (getcwd() !== $tmpDirectory) {
    die("Unable to change directory");
}
exec("rm -rf ./*");

$css = [];
$css[] = '// This file is auto generated by scripts/make-homepage-sprites.php';
$css[] = '.homesprite {
    float:left;
    display:inline-block;
    background: url("@{assetUrl}img/'.$imgFilename.'") no-repeat;
    background-size: 200px;
    width:200px;
    height:200px;
}';

$images = [];

// Load the images from a CtrlV album
/*$albumId = 2922;
$url = "http://api.ctrlv.vagrant/albums/{$albumId}/images?limit=20";
if (!$result = file_get_contents($url)) {
    die("Unable to load images from API");
}
if (!$result = json_decode($result)) {
    die("Unable to parse API response");
}

if (empty($result->images)) {
    die("No images found in album");
}

foreach ($result->images as $i => $image) {
    $url = $image->image->url;

    $ext = substr($url, strrpos($url, '.'));
    $file = md5($url) . $ext;

    // Download image
    //passthru("wget -O {$file} {$image->image->url}");

    $images[] = $tmpDirectory.'/'.$file;
}*/

// Load the images from a directory
$srcDir = dirname(__DIR__).'/src/img/homepage';
$images = scandir($srcDir);

$images = array_filter($images, function ($image) {
    return stripos($image, '.') !== 0;
});

$images = array_map(function (&$image) use ($srcDir) {
    return $srcDir.'/'.$image;
}, $images);

sort($images);
print_r($images);

$tmpImages = [];
foreach ($images as $i => $image) {
    // Convert to 400x400
    $file = uniqid().'.jpg';
    $tmpImages[] = $file;
    $cmd = 'convert '.$image.' -resize "400^>" -gravity center -crop 400x400+0+0 '.$file;
    echo $cmd . PHP_EOL;
    passthru($cmd);

    $y = 200 * $i;
    $css[] = ".homesprite-{$i} {
    background-position: 0 -{$y}px;
}";
}

$tmpImages = "'" . implode("' '", $tmpImages) . "'";
$cmd = 'montage ' . $tmpImages . ' -background transparent -mode Concatenate -tile 1x -geometry +0+0 '.$imgFileDir.'/'.$imgFilename;

echo $cmd . PHP_EOL;

passthru($cmd);

file_put_contents($lessFilePath, implode("\n", $css));
